name: Create Tag from Commit Message

on:
  push:
    branches:
      - main

jobs:
  create_tag_if_needed:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Required to push tags

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get last commit message
        id: get_commit
        run: |
          echo "commit_message=$(git log -1 --pretty=format:%s)" >> $GITHUB_ENV

      - name: Check if commit message contains 'create a tag :'
        id: check_tag
        run: |
          if [[ "$commit_message" =~ create\ a\ tag\ :\ ([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            echo "tag_version=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
            echo "tag_found=true" >> $GITHUB_ENV
          else
            echo "tag_found=false" >> $GITHUB_ENV
          fi

      - name: Create and push tag
        if: env.tag_found == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ steps.check_tag.outputs.tag_version }}
          git push origin ${{ steps.check_tag.outputs.tag_version }}
